-- ========================================================
-- EcoHotel OS - Oracle SQL Relational Database Schema
-- Course: BMSE2073 Software Design and Architecture
-- Mandate: Visit Malaysia 2026 (VM2026 Directive)
-- ========================================================

-- Table: USERS
CREATE TABLE USERS (
    ID VARCHAR2(64) PRIMARY KEY,
    USERNAME VARCHAR2(255),
    PASSWORD VARCHAR2(255),
    NAME VARCHAR2(255),
    ROLE VARCHAR2(255),
    DEPARTMENT VARCHAR2(255),
    AVATAR VARCHAR2(255)
);

INSERT INTO USERS (ID,USERNAME,PASSWORD,NAME,ROLE,DEPARTMENT,AVATAR) VALUES ('USR-100','admin','password123','Sarah Chen','Operations Director','Executive Board','SC');
INSERT INTO USERS (ID,USERNAME,PASSWORD,NAME,ROLE,DEPARTMENT,AVATAR) VALUES ('USR-101','exec','password123','Kar Hang','Sustainability Executive','Executive Board','KH');
INSERT INTO USERS (ID,USERNAME,PASSWORD,NAME,ROLE,DEPARTMENT,AVATAR) VALUES ('USR-102','tech','password123','Zhen Bang','Tech Lead','IT','ZB');
INSERT INTO USERS (ID,USERNAME,PASSWORD,NAME,ROLE,DEPARTMENT,AVATAR) VALUES ('USR-103','fac','password123','Wan Ching','Facilities Manager','Engineering','WC');
INSERT INTO USERS (ID,USERNAME,PASSWORD,NAME,ROLE,DEPARTMENT,AVATAR) VALUES ('USR-104','chef','password123','Sze Ping','Head Chef','F&B','SP');
INSERT INTO USERS (ID,USERNAME,PASSWORD,NAME,ROLE,DEPARTMENT,AVATAR) VALUES ('USR-105','guest','password123','Simon Wong','Guest','Guest','SW');

COMMIT;

-- Table: BASELINES
CREATE TABLE BASELINES (
    ID VARCHAR2(64) PRIMARY KEY,
    KEY VARCHAR2(255),
    NAME VARCHAR2(255),
    VALUE NUMBER(10),
    UNIT VARCHAR2(255),
    CATEGORY VARCHAR2(255),
    UPDATEDBY VARCHAR2(255),
    UPDATEDAT VARCHAR2(255)
);

INSERT INTO BASELINES (ID,KEY,NAME,VALUE,UNIT,CATEGORY,UPDATEDBY,UPDATEDAT) VALUES ('BL-01','water_per_room','Standard Water Consumption per Room',180,'L/occupied room/day','Water','Zhen Bang','2026-08-01 10:00');
INSERT INTO BASELINES (ID,KEY,NAME,VALUE,UNIT,CATEGORY,UPDATEDBY,UPDATEDAT) VALUES ('BL-02','power_per_room','Standard Electricity per Room',12.5,'kWh/occupied room/day','Electricity','Kar Hang','2026-08-01 10:00');
INSERT INTO BASELINES (ID,KEY,NAME,VALUE,UNIT,CATEGORY,UPDATEDBY,UPDATEDAT) VALUES ('BL-03','kitchen_water','Main Kitchen Daily Water Baseline',4500,'L/day','Water','Wan Ching','2026-08-02 09:30');
INSERT INTO BASELINES (ID,KEY,NAME,VALUE,UNIT,CATEGORY,UPDATEDBY,UPDATEDAT) VALUES ('BL-04','kitchen_power','Main Kitchen Daily Electricity Baseline',380,'kWh/day','Electricity','Wan Ching','2026-08-02 09:30');
INSERT INTO BASELINES (ID,KEY,NAME,VALUE,UNIT,CATEGORY,UPDATEDBY,UPDATEDAT) VALUES ('BL-05','buffet_food_waste','Max Allowed Food Waste per Diner',0.12,'kg/guest/service','F&B','Sze Ping','2026-08-03 14:15');
INSERT INTO BASELINES (ID,KEY,NAME,VALUE,UNIT,CATEGORY,UPDATEDBY,UPDATEDAT) VALUES ('BL-06','laundry_water','Commercial Laundry Water Baseline',6200,'L/day','Water','Wan Ching','2026-08-01 10:00');
INSERT INTO BASELINES (ID,KEY,NAME,VALUE,UNIT,CATEGORY,UPDATEDBY,UPDATEDAT) VALUES ('BL-07','hvac_chiller_power','Central Chilled Water HVAC Baseline',850,'kWh/day','Electricity','Wan Ching','2026-08-05 11:20');
INSERT INTO BASELINES (ID,KEY,NAME,VALUE,UNIT,CATEGORY,UPDATEDBY,UPDATEDAT) VALUES ('BL-08','laundry_power','Commercial Laundry Power Baseline',290,'kWh/day','Electricity','Wan Ching','2026-08-01 10:00');
INSERT INTO BASELINES (ID,KEY,NAME,VALUE,UNIT,CATEGORY,UPDATEDBY,UPDATEDAT) VALUES ('BL-09','pool_water','Pool Filtration Daily Top-up Baseline',800,'L/day','Water','System','2026-07-15 10:00');
INSERT INTO BASELINES (ID,KEY,NAME,VALUE,UNIT,CATEGORY,UPDATEDBY,UPDATEDAT) VALUES ('BL-10','lobby_hvac','Lobby HVAC Energy Baseline',120,'kWh/day','Electricity','System','2026-07-15 10:00');
INSERT INTO BASELINES (ID,KEY,NAME,VALUE,UNIT,CATEGORY,UPDATEDBY,UPDATEDAT) VALUES ('BL-11','floor1_water','Floor 1 Guest Wing Water Baseline',1800,'L/day','Water','Wan Ching','2026-08-01 10:00');
INSERT INTO BASELINES (ID,KEY,NAME,VALUE,UNIT,CATEGORY,UPDATEDBY,UPDATEDAT) VALUES ('BL-12','floor1_power','Floor 1 Guest Wing Electricity Baseline',140,'kWh/day','Electricity','Wan Ching','2026-08-01 10:00');
INSERT INTO BASELINES (ID,KEY,NAME,VALUE,UNIT,CATEGORY,UPDATEDBY,UPDATEDAT) VALUES ('BL-13','floor2_water','Floor 2 Guest Wing Water Baseline',1750,'L/day','Water','Wan Ching','2026-08-01 10:00');
INSERT INTO BASELINES (ID,KEY,NAME,VALUE,UNIT,CATEGORY,UPDATEDBY,UPDATEDAT) VALUES ('BL-14','floor2_power','Floor 2 Guest Wing Electricity Baseline',145,'kWh/day','Electricity','Wan Ching','2026-08-01 10:00');
INSERT INTO BASELINES (ID,KEY,NAME,VALUE,UNIT,CATEGORY,UPDATEDBY,UPDATEDAT) VALUES ('BL-15','floor3_water','Floor 3 Executive Wing Water Baseline',1600,'L/day','Water','Wan Ching','2026-08-01 10:00');
INSERT INTO BASELINES (ID,KEY,NAME,VALUE,UNIT,CATEGORY,UPDATEDBY,UPDATEDAT) VALUES ('BL-16','facilities_workshop_water','Maintenance Workshop Water Baseline',500,'L/day','Water','Wan Ching','2026-08-01 10:00');
INSERT INTO BASELINES (ID,KEY,NAME,VALUE,UNIT,CATEGORY,UPDATEDBY,UPDATEDAT) VALUES ('BL-17','front_office_water','Front Office & Lobby Water Baseline',700,'L/day','Water','Wan Ching','2026-08-01 10:00');

COMMIT;

-- Table: COMPLIANCE_LOG
CREATE TABLE COMPLIANCE_LOG (
    MONTH VARCHAR2(255),
    FOODSAVEDKG NUMBER(10),
    WATERCONSERVEDL NUMBER(10),
    ENERGYSAVEDKWH NUMBER(10),
    CO2AVOIDEDKG NUMBER(10),
    COSTSAVEDMYR NUMBER(10),
    VMSCORE NUMBER(10),
    STATUS VARCHAR2(255)
);

INSERT INTO COMPLIANCE_LOG (MONTH,FOODSAVEDKG,WATERCONSERVEDL,ENERGYSAVEDKWH,CO2AVOIDEDKG,COSTSAVEDMYR,VMSCORE,STATUS) VALUES ('Oct 2025',910,112000,9800,13500,25100,68,'Needs Improvement');
INSERT INTO COMPLIANCE_LOG (MONTH,FOODSAVEDKG,WATERCONSERVEDL,ENERGYSAVEDKWH,CO2AVOIDEDKG,COSTSAVEDMYR,VMSCORE,STATUS) VALUES ('Nov 2025',980,118000,10200,14200,27300,71,'Acceptable');
INSERT INTO COMPLIANCE_LOG (MONTH,FOODSAVEDKG,WATERCONSERVEDL,ENERGYSAVEDKWH,CO2AVOIDEDKG,COSTSAVEDMYR,VMSCORE,STATUS) VALUES ('Dec 2025',1050,125000,10900,15400,29500,74,'Acceptable');
INSERT INTO COMPLIANCE_LOG (MONTH,FOODSAVEDKG,WATERCONSERVEDL,ENERGYSAVEDKWH,CO2AVOIDEDKG,COSTSAVEDMYR,VMSCORE,STATUS) VALUES ('Jan 2026',1120,134000,11500,16800,31200,75,'Compliant');
INSERT INTO COMPLIANCE_LOG (MONTH,FOODSAVEDKG,WATERCONSERVEDL,ENERGYSAVEDKWH,CO2AVOIDEDKG,COSTSAVEDMYR,VMSCORE,STATUS) VALUES ('Feb 2026',1190,139000,12100,17600,32800,76,'Compliant');
INSERT INTO COMPLIANCE_LOG (MONTH,FOODSAVEDKG,WATERCONSERVEDL,ENERGYSAVEDKWH,CO2AVOIDEDKG,COSTSAVEDMYR,VMSCORE,STATUS) VALUES ('Mar 2026',1240,145000,12800,18450,34200,78,'Compliant');
INSERT INTO COMPLIANCE_LOG (MONTH,FOODSAVEDKG,WATERCONSERVEDL,ENERGYSAVEDKWH,CO2AVOIDEDKG,COSTSAVEDMYR,VMSCORE,STATUS) VALUES ('Apr 2026',1480,168000,14200,21300,39800,84,'High Compliance');
INSERT INTO COMPLIANCE_LOG (MONTH,FOODSAVEDKG,WATERCONSERVEDL,ENERGYSAVEDKWH,CO2AVOIDEDKG,COSTSAVEDMYR,VMSCORE,STATUS) VALUES ('May 2026',1620,192000,16500,24100,44600,89,'High Compliance');
INSERT INTO COMPLIANCE_LOG (MONTH,FOODSAVEDKG,WATERCONSERVEDL,ENERGYSAVEDKWH,CO2AVOIDEDKG,COSTSAVEDMYR,VMSCORE,STATUS) VALUES ('Jun 2026',1510,178000,15300,22600,41200,86,'High Compliance');
INSERT INTO COMPLIANCE_LOG (MONTH,FOODSAVEDKG,WATERCONSERVEDL,ENERGYSAVEDKWH,CO2AVOIDEDKG,COSTSAVEDMYR,VMSCORE,STATUS) VALUES ('Jul 2026',1790,215000,18900,27800,49500,93,'VM2026 Champion');
INSERT INTO COMPLIANCE_LOG (MONTH,FOODSAVEDKG,WATERCONSERVEDL,ENERGYSAVEDKWH,CO2AVOIDEDKG,COSTSAVEDMYR,VMSCORE,STATUS) VALUES ('Aug 2026 (MTD)',940,122000,10400,15200,28400,92,'On Track');

COMMIT;

-- Table: RAW_INGREDIENTS
CREATE TABLE RAW_INGREDIENTS (
    ID VARCHAR2(64) PRIMARY KEY,
    NAME VARCHAR2(255),
    CATEGORY VARCHAR2(255),
    QUANTITY NUMBER(10),
    UNIT VARCHAR2(255),
    BATCHNUMBER VARCHAR2(255),
    DELIVERYDATE VARCHAR2(255),
    EXPIRYDATE VARCHAR2(255),
    SHELFLIFEDAYS NUMBER(10),
    COSTPERKG NUMBER(12,2),
    STORAGELOCATION VARCHAR2(255)
);

INSERT INTO RAW_INGREDIENTS (ID,NAME,CATEGORY,QUANTITY,UNIT,BATCHNUMBER,DELIVERYDATE,EXPIRYDATE,SHELFLIFEDAYS,COSTPERKG,STORAGELOCATION) VALUES ('ING-001','Fresh Farm Poultry (Chicken Breast)','Meat & Poultry',65,'kg','BCH-20260810-CK','2026-08-10','2026-08-14',4,16.5,'Walk-in Chiller A');
INSERT INTO RAW_INGREDIENTS (ID,NAME,CATEGORY,QUANTITY,UNIT,BATCHNUMBER,DELIVERYDATE,EXPIRYDATE,SHELFLIFEDAYS,COSTPERKG,STORAGELOCATION) VALUES ('ING-002','Atlantic Salmon Fillet','Seafood',28.5,'kg','BCH-20260811-SL','2026-08-11','2026-08-13',2,48,'Walk-in Chiller A');
INSERT INTO RAW_INGREDIENTS (ID,NAME,CATEGORY,QUANTITY,UNIT,BATCHNUMBER,DELIVERYDATE,EXPIRYDATE,SHELFLIFEDAYS,COSTPERKG,STORAGELOCATION) VALUES ('ING-003','Grade A Omega-3 Eggs','Dairy & Eggs',450,'units','BCH-20260808-EG','2026-08-08','2026-08-18',10,0.65,'Dry Storage Cold Zone');
INSERT INTO RAW_INGREDIENTS (ID,NAME,CATEGORY,QUANTITY,UNIT,BATCHNUMBER,DELIVERYDATE,EXPIRYDATE,SHELFLIFEDAYS,COSTPERKG,STORAGELOCATION) VALUES ('ING-004','Cameron Highland Hydroponic Lettuce','Produce',18,'kg','BCH-20260812-LT','2026-08-12','2026-08-15',3,9.2,'Vegetable Crisper B');
INSERT INTO RAW_INGREDIENTS (ID,NAME,CATEGORY,QUANTITY,UNIT,BATCHNUMBER,DELIVERYDATE,EXPIRYDATE,SHELFLIFEDAYS,COSTPERKG,STORAGELOCATION) VALUES ('ING-005','Fragrant Jasmine Rice (Siam Super)','Grains & Dry',220,'kg','BCH-20260720-RC','2026-07-20','2026-12-31',164,4.8,'Dry Bulk Store');
INSERT INTO RAW_INGREDIENTS (ID,NAME,CATEGORY,QUANTITY,UNIT,BATCHNUMBER,DELIVERYDATE,EXPIRYDATE,SHELFLIFEDAYS,COSTPERKG,STORAGELOCATION) VALUES ('ING-006','Organic Coconut Milk (Santan)','Dairy & Oils',35,'L','BCH-20260809-SM','2026-08-09','2026-08-14',5,8.5,'Walk-in Chiller B');
INSERT INTO RAW_INGREDIENTS (ID,NAME,CATEGORY,QUANTITY,UNIT,BATCHNUMBER,DELIVERYDATE,EXPIRYDATE,SHELFLIFEDAYS,COSTPERKG,STORAGELOCATION) VALUES ('ING-007','Australian Ribeye Beef Strips','Meat & Poultry',32,'kg','BCH-20260805-BF','2026-08-05','2026-08-19',14,62,'Deep Freezer -18C');
INSERT INTO RAW_INGREDIENTS (ID,NAME,CATEGORY,QUANTITY,UNIT,BATCHNUMBER,DELIVERYDATE,EXPIRYDATE,SHELFLIFEDAYS,COSTPERKG,STORAGELOCATION) VALUES ('ING-008','Fresh Tiger Prawns (Grade L)','Seafood',15,'kg','BCH-20260812-PW','2026-08-12','2026-08-14',2,52,'Walk-in Chiller A');
INSERT INTO RAW_INGREDIENTS (ID,NAME,CATEGORY,QUANTITY,UNIT,BATCHNUMBER,DELIVERYDATE,EXPIRYDATE,SHELFLIFEDAYS,COSTPERKG,STORAGELOCATION) VALUES ('ING-009','Organic Yellow Noodle (Mee)','Grains & Dry',40,'kg','BCH-20260811-ND','2026-08-11','2026-08-16',5,5.5,'Dry Pantry Zone 1');
INSERT INTO RAW_INGREDIENTS (ID,NAME,CATEGORY,QUANTITY,UNIT,BATCHNUMBER,DELIVERYDATE,EXPIRYDATE,SHELFLIFEDAYS,COSTPERKG,STORAGELOCATION) VALUES ('ING-010','Vine-Ripened Cameron Tomatoes','Produce',24,'kg','BCH-20260811-TM','2026-08-11','2026-08-16',5,7.8,'Vegetable Crisper B');

COMMIT;

-- Table: FOOD_WASTE_LOGS
CREATE TABLE FOOD_WASTE_LOGS (
    ID VARCHAR2(64) PRIMARY KEY,
    DEPARTMENTID VARCHAR2(255),
    DATE VARCHAR2(255),
    MEALPERIOD VARCHAR2(255),
    ITEM VARCHAR2(255),
    TYPE VARCHAR2(255),
    REASON VARCHAR2(255),
    QUANTITY NUMBER(12,2),
    UNIT VARCHAR2(255),
    COSTIMPACT NUMBER(12,2),
    LOGGEDBY VARCHAR2(255)
);

INSERT INTO FOOD_WASTE_LOGS (ID,DEPARTMENTID,DATE,MEALPERIOD,ITEM,TYPE,REASON,QUANTITY,UNIT,COSTIMPACT,LOGGEDBY) VALUES ('WST-101','kitchen','2026-08-12','Dinner Shift','Cameron Highland Hydroponic Lettuce','Spoilage','Expired / Wilted in Chiller B',3.4,'kg',31.28,'Sze Ping (Head Chef)');
INSERT INTO FOOD_WASTE_LOGS (ID,DEPARTMENTID,DATE,MEALPERIOD,ITEM,TYPE,REASON,QUANTITY,UNIT,COSTIMPACT,LOGGEDBY) VALUES ('WST-102','kitchen','2026-08-12','Dinner Shift','Fresh Farm Poultry','Prep Waste','Bones & Trimmings',5.8,'kg',0,'Kitchen Prep Team');
INSERT INTO FOOD_WASTE_LOGS (ID,DEPARTMENTID,DATE,MEALPERIOD,ITEM,TYPE,REASON,QUANTITY,UNIT,COSTIMPACT,LOGGEDBY) VALUES ('WST-103','kitchen','2026-08-11','Breakfast Shift','Organic Coconut Milk','Spoilage','Sour batch due to door left ajar',4,'L',34,'Sous Chef Ahmad');
INSERT INTO FOOD_WASTE_LOGS (ID,DEPARTMENTID,DATE,MEALPERIOD,ITEM,TYPE,REASON,QUANTITY,UNIT,COSTIMPACT,LOGGEDBY) VALUES ('WST-104','kitchen','2026-08-11','Breakfast Shift','Grade A Omega-3 Eggs','Prep Waste','Eggshells sent to composter',6.2,'kg',0,'Prep Cook Mei');
INSERT INTO FOOD_WASTE_LOGS (ID,DEPARTMENTID,DATE,MEALPERIOD,ITEM,TYPE,REASON,QUANTITY,UNIT,COSTIMPACT,LOGGEDBY) VALUES ('WST-105','kitchen','2026-08-10','Dinner Shift','Atlantic Salmon Skin & Bones','Prep Waste','Fish stock extraction',4.5,'kg',0,'Sous Chef Ahmad');
INSERT INTO FOOD_WASTE_LOGS (ID,DEPARTMENTID,DATE,MEALPERIOD,ITEM,TYPE,REASON,QUANTITY,UNIT,COSTIMPACT,LOGGEDBY) VALUES ('FW-111','kitchen','2026-08-12',NULL,'Mixed Prep','Preparation Scrap',NULL,12.4,'kg',NULL,'Sous Chef');
INSERT INTO FOOD_WASTE_LOGS (ID,DEPARTMENTID,DATE,MEALPERIOD,ITEM,TYPE,REASON,QUANTITY,UNIT,COSTIMPACT,LOGGEDBY) VALUES ('FW-112','kitchen','2026-08-12',NULL,'Dairy','Spoilage',NULL,3.2,'kg',NULL,'Inventory Clerk');
INSERT INTO FOOD_WASTE_LOGS (ID,DEPARTMENTID,DATE,MEALPERIOD,ITEM,TYPE,REASON,QUANTITY,UNIT,COSTIMPACT,LOGGEDBY) VALUES ('FW-113','kitchen','2026-08-12',NULL,'Buffet Leftover','Spoilage',NULL,8.5,'kg',NULL,'F&B Manager');

COMMIT;

-- Table: DISHES
CREATE TABLE DISHES (
    ID VARCHAR2(64) PRIMARY KEY,
    NAME VARCHAR2(255),
    CATEGORY VARCHAR2(255),
    BASEPERGUESTGRAMS NUMBER(10),
    INGREDIENTREFS VARCHAR2(1000),
    HISTORICALWASTERATE NUMBER(12,2),
    WASTEMULTIPLIER NUMBER(12,2),
    COSTTIER VARCHAR2(255)
);

INSERT INTO DISHES (ID,NAME,CATEGORY,BASEPERGUESTGRAMS,INGREDIENTREFS,HISTORICALWASTERATE,WASTEMULTIPLIER,COSTTIER) VALUES ('DSH-01','Traditional Nasi Lemak w/ Rendang','Main / Asian',160,'["Jasmine Rice", "Chicken", "Coconut Milk"]',0.04,0.96,'Medium');
INSERT INTO DISHES (ID,NAME,CATEGORY,BASEPERGUESTGRAMS,INGREDIENTREFS,HISTORICALWASTERATE,WASTEMULTIPLIER,COSTTIER) VALUES ('DSH-02','Grilled Herb Butter Atlantic Salmon','Western Grill',110,'["Salmon Fillet", "Butter", "Herbs"]',0.14,0.86,'High');
INSERT INTO DISHES (ID,NAME,CATEGORY,BASEPERGUESTGRAMS,INGREDIENTREFS,HISTORICALWASTERATE,WASTEMULTIPLIER,COSTTIER) VALUES ('DSH-03','Live Omelette & Scrambled Egg Station','Live Station',90,'["Eggs", "Dairy", "Vegetables"]',0.05,0.95,'Low');
INSERT INTO DISHES (ID,NAME,CATEGORY,BASEPERGUESTGRAMS,INGREDIENTREFS,HISTORICALWASTERATE,WASTEMULTIPLIER,COSTTIER) VALUES ('DSH-04','Wok-Tossed Tiger Prawn Mee Mamak','Asian Noodle',130,'["Tiger Prawns", "Yellow Noodle", "Spices"]',0.08,0.92,'High');
INSERT INTO DISHES (ID,NAME,CATEGORY,BASEPERGUESTGRAMS,INGREDIENTREFS,HISTORICALWASTERATE,WASTEMULTIPLIER,COSTTIER) VALUES ('DSH-05','Crispy Organic Garden Salad Bar','Salad / Cold',75,'["Hydroponic Lettuce", "Tomatoes", "Dressing"]',0.18,0.82,'Low');
INSERT INTO DISHES (ID,NAME,CATEGORY,BASEPERGUESTGRAMS,INGREDIENTREFS,HISTORICALWASTERATE,WASTEMULTIPLIER,COSTTIER) VALUES ('DSH-06','Slow-Roasted Australian Beef Striploin','Carvery',120,'["Beef Strips", "Rosemary Jus"]',0.12,0.88,'High');

COMMIT;

-- Table: PLATE_WASTE
CREATE TABLE PLATE_WASTE (
    ID VARCHAR2(64) PRIMARY KEY,
    DATE VARCHAR2(255),
    MEALPERIOD VARCHAR2(255),
    DISHID VARCHAR2(255),
    DISHNAME VARCHAR2(255),
    DISCARDEDKG NUMBER(12,2),
    ISANOMALY NUMBER(10),
    NOTE VARCHAR2(255),
    LOGGEDBY VARCHAR2(255)
);

INSERT INTO PLATE_WASTE (ID,DATE,MEALPERIOD,DISHID,DISHNAME,DISCARDEDKG,ISANOMALY,NOTE,LOGGEDBY) VALUES ('PW-001','2026-08-12','Dinner','DSH-02','Grilled Herb Butter Atlantic Salmon',4.8,False,'Slight over-batching during late dinner peak','Chef Zhen Bang');
INSERT INTO PLATE_WASTE (ID,DATE,MEALPERIOD,DISHID,DISHNAME,DISCARDEDKG,ISANOMALY,NOTE,LOGGEDBY) VALUES ('PW-002','2026-08-12','Dinner','DSH-05','Crispy Organic Garden Salad Bar',3.2,False,'Guests preferred warm appetizers due to rain','Prep Cook Mei');
INSERT INTO PLATE_WASTE (ID,DATE,MEALPERIOD,DISHID,DISHNAME,DISCARDEDKG,ISANOMALY,NOTE,LOGGEDBY) VALUES ('PW-003','2026-08-11','Dinner','DSH-06','Slow-Roasted Australian Beef Striploin',6.5,True,NULL,'Chef Zhen Bang');
INSERT INTO PLATE_WASTE (ID,DATE,MEALPERIOD,DISHID,DISHNAME,DISCARDEDKG,ISANOMALY,NOTE,LOGGEDBY) VALUES ('PW-101','2026-08-12','Room Service',NULL,NULL,0.8,NULL,NULL,NULL);
INSERT INTO PLATE_WASTE (ID,DATE,MEALPERIOD,DISHID,DISHNAME,DISCARDEDKG,ISANOMALY,NOTE,LOGGEDBY) VALUES ('PW-102','2026-08-12','Room Service',NULL,NULL,1.2,NULL,NULL,NULL);
INSERT INTO PLATE_WASTE (ID,DATE,MEALPERIOD,DISHID,DISHNAME,DISCARDEDKG,ISANOMALY,NOTE,LOGGEDBY) VALUES ('PW-103','2026-08-12','Room Service',NULL,NULL,0.5,NULL,NULL,NULL);
INSERT INTO PLATE_WASTE (ID,DATE,MEALPERIOD,DISHID,DISHNAME,DISCARDEDKG,ISANOMALY,NOTE,LOGGEDBY) VALUES ('PW-104','2026-08-12','Room Service',NULL,NULL,2.1,NULL,NULL,NULL);
INSERT INTO PLATE_WASTE (ID,DATE,MEALPERIOD,DISHID,DISHNAME,DISCARDEDKG,ISANOMALY,NOTE,LOGGEDBY) VALUES ('PW-105','2026-08-12','Room Service',NULL,NULL,0.4,NULL,NULL,NULL);

COMMIT;

-- Table: ROOM_SCHEDULE
CREATE TABLE ROOM_SCHEDULE (
    ROOMNUMBER VARCHAR2(255),
    FLOOR NUMBER(10),
    TYPE VARCHAR2(255),
    GUESTNAME VARCHAR2(255),
    STATUS VARCHAR2(255),
    SERVICEPREFERENCE VARCHAR2(255),
    OPTOUTDAYS NUMBER(10),
    LINENDELAYDAYS NUMBER(10),
    TOWELREUSE NUMBER(10),
    CLEANINGSTATUS VARCHAR2(255),
    ECOPOINTSEARNED NUMBER(10),
    QRTOKEN VARCHAR2(255)
);

INSERT INTO ROOM_SCHEDULE (ROOMNUMBER,FLOOR,TYPE,GUESTNAME,STATUS,SERVICEPREFERENCE,OPTOUTDAYS,LINENDELAYDAYS,TOWELREUSE,CLEANINGSTATUS,ECOPOINTSEARNED,QRTOKEN) VALUES ('101',1,'Deluxe Ocean Suite','Tan Sri Jeffrey Cheah','Occupied','STANDARD',0,0,False,'Active Clean List',0,'RM101-SEC-771');
INSERT INTO ROOM_SCHEDULE (ROOMNUMBER,FLOOR,TYPE,GUESTNAME,STATUS,SERVICEPREFERENCE,OPTOUTDAYS,LINENDELAYDAYS,TOWELREUSE,CLEANINGSTATUS,ECOPOINTSEARNED,QRTOKEN) VALUES ('102',1,'Deluxe Garden View','Elena Rostova','Occupied','OPT_OUT_CLEANING',1,2,True,'Skipped (Opt-Out)',20,'RM102-SEC-892');
INSERT INTO ROOM_SCHEDULE (ROOMNUMBER,FLOOR,TYPE,GUESTNAME,STATUS,SERVICEPREFERENCE,OPTOUTDAYS,LINENDELAYDAYS,TOWELREUSE,CLEANINGSTATUS,ECOPOINTSEARNED,QRTOKEN) VALUES ('103',1,'Deluxe Garden View','Kenji Sato','Occupied','STANDARD',0,0,True,'Active Clean List',5,'RM103-SEC-554');
INSERT INTO ROOM_SCHEDULE (ROOMNUMBER,FLOOR,TYPE,GUESTNAME,STATUS,SERVICEPREFERENCE,OPTOUTDAYS,LINENDELAYDAYS,TOWELREUSE,CLEANINGSTATUS,ECOPOINTSEARNED,QRTOKEN) VALUES ('201',2,'Premier Sunset Villa','Michael & Sarah Davies','Occupied','LINEN_DELAY',0,3,True,'Light Service Only',10,'RM201-SEC-340');
INSERT INTO ROOM_SCHEDULE (ROOMNUMBER,FLOOR,TYPE,GUESTNAME,STATUS,SERVICEPREFERENCE,OPTOUTDAYS,LINENDELAYDAYS,TOWELREUSE,CLEANINGSTATUS,ECOPOINTSEARNED,QRTOKEN) VALUES ('202',2,'Premier Sunset Villa','Dr. Farouk Abdullah','Occupied','OPT_OUT_CLEANING',2,2,True,'Skipped (Opt-Out)',30,'RM202-SEC-512');
INSERT INTO ROOM_SCHEDULE (ROOMNUMBER,FLOOR,TYPE,GUESTNAME,STATUS,SERVICEPREFERENCE,OPTOUTDAYS,LINENDELAYDAYS,TOWELREUSE,CLEANINGSTATUS,ECOPOINTSEARNED,QRTOKEN) VALUES ('203',2,'Premier Sunset Villa','Amina Al-Mansoor','Occupied','STANDARD',0,0,False,'Active Clean List',0,'RM203-SEC-918');
INSERT INTO ROOM_SCHEDULE (ROOMNUMBER,FLOOR,TYPE,GUESTNAME,STATUS,SERVICEPREFERENCE,OPTOUTDAYS,LINENDELAYDAYS,TOWELREUSE,CLEANINGSTATUS,ECOPOINTSEARNED,QRTOKEN) VALUES ('301',3,'Presidential Eco Suite','Hans Zimmer & Family','Occupied','STANDARD',0,0,True,'Active Clean List',5,'RM301-SEC-901');
INSERT INTO ROOM_SCHEDULE (ROOMNUMBER,FLOOR,TYPE,GUESTNAME,STATUS,SERVICEPREFERENCE,OPTOUTDAYS,LINENDELAYDAYS,TOWELREUSE,CLEANINGSTATUS,ECOPOINTSEARNED,QRTOKEN) VALUES ('302',3,'Deluxe Ocean Suite','Vacant Ready','Vacant Ready','STANDARD',0,0,False,'Inspection Passed',0,'RM302-SEC-110');
INSERT INTO ROOM_SCHEDULE (ROOMNUMBER,FLOOR,TYPE,GUESTNAME,STATUS,SERVICEPREFERENCE,OPTOUTDAYS,LINENDELAYDAYS,TOWELREUSE,CLEANINGSTATUS,ECOPOINTSEARNED,QRTOKEN) VALUES ('303',3,'Executive Seaview Room','Chloe Dupont','Occupied','LINEN_DELAY',0,2,True,'Light Service Only',15,'RM303-SEC-337');
INSERT INTO ROOM_SCHEDULE (ROOMNUMBER,FLOOR,TYPE,GUESTNAME,STATUS,SERVICEPREFERENCE,OPTOUTDAYS,LINENDELAYDAYS,TOWELREUSE,CLEANINGSTATUS,ECOPOINTSEARNED,QRTOKEN) VALUES ('304',3,'Executive Seaview Room','Simon Wong (Demo Tourist)','Occupied','OPT_OUT_CLEANING',1,2,True,'Skipped (Opt-Out)',25,'RM304-SEC-426');

COMMIT;

-- Table: ECO_VOUCHERS
CREATE TABLE ECO_VOUCHERS (
    CODE VARCHAR2(255),
    ROOMNUMBER VARCHAR2(255),
    GUESTNAME VARCHAR2(255),
    REWARDTITLE VARCHAR2(255),
    DESCRIPTION VARCHAR2(255),
    POINTSCOST NUMBER(10),
    ISSUEDATE VARCHAR2(255),
    EXPIRYDATE VARCHAR2(255),
    ISREDEEMED NUMBER(10)
);

INSERT INTO ECO_VOUCHERS (CODE,ROOMNUMBER,GUESTNAME,REWARDTITLE,DESCRIPTION,POINTSCOST,ISSUEDATE,EXPIRYDATE,ISREDEEMED) VALUES ('VM26-ECO-7821','304','Simon Wong','15% Sustainable Dining Voucher','Valid at Ocean Reef Organic Bistro & Farm-to-Table Kitchen',25,'2026-08-13 07:15','2026-08-20',False);
INSERT INTO ECO_VOUCHERS (CODE,ROOMNUMBER,GUESTNAME,REWARDTITLE,DESCRIPTION,POINTSCOST,ISSUEDATE,EXPIRYDATE,ISREDEEMED) VALUES ('VM26-TRP-4409','202','Dr. Farouk Abdullah','Langkawi UNESCO Geopark Mangrove Pass','Zero-emission solar boat eco-safari guided expedition',30,'2026-08-12 16:30','2026-08-25',False);

COMMIT;

-- Table: GUEST_INTERACTION_LOG
CREATE TABLE GUEST_INTERACTION_LOG (
    ID VARCHAR2(64) PRIMARY KEY,
    ROOMNUMBER VARCHAR2(255),
    TIMESTAMP VARCHAR2(255),
    ACTION VARCHAR2(255),
    DETAILS VARCHAR2(255),
    POINTSEARNED NUMBER(10)
);

INSERT INTO GUEST_INTERACTION_LOG (ID,ROOMNUMBER,TIMESTAMP,ACTION,DETAILS,POINTSEARNED) VALUES ('GIL-001','304','2026-08-13 08:30:00','PWA_SERVICE_SELECTION','Selected Opt-Out Daily Cleaning + Towel Reuse',20);
INSERT INTO GUEST_INTERACTION_LOG (ID,ROOMNUMBER,TIMESTAMP,ACTION,DETAILS,POINTSEARNED) VALUES ('GIL-002','202','2026-08-12 16:30:15','VOUCHER_GENERATED','Milestone reached (30 pts) -> Voucher VM26-TRP-4409 generated',0);
INSERT INTO GUEST_INTERACTION_LOG (ID,ROOMNUMBER,TIMESTAMP,ACTION,DETAILS,POINTSEARNED) VALUES ('GIL-003','102','2026-08-12 18:20:44','PWA_SERVICE_SELECTION','Selected Opt-Out Daily Cleaning + Towel Reuse',20);
INSERT INTO GUEST_INTERACTION_LOG (ID,ROOMNUMBER,TIMESTAMP,ACTION,DETAILS,POINTSEARNED) VALUES ('GIL-004','201','2026-08-12 19:10:02','PWA_SERVICE_SELECTION','Selected Linen Delay (3 days) + Towel Reuse',15);

COMMIT;

-- Table: METER_READINGS
CREATE TABLE METER_READINGS (
    METERID VARCHAR2(255),
    DEPARTMENTID VARCHAR2(255),
    ZONE VARCHAR2(255),
    TYPE VARCHAR2(255),
    BASELINEDAILY NUMBER(10),
    UNIT VARCHAR2(255),
    LASTREADING NUMBER(10),
    LASTREADINGTIME VARCHAR2(255),
    STATUS VARCHAR2(255),
    ICON VARCHAR2(255)
);

INSERT INTO METER_READINGS (METERID,DEPARTMENTID,ZONE,TYPE,BASELINEDAILY,UNIT,LASTREADING,LASTREADINGTIME,STATUS,ICON) VALUES ('MTR-W-F1','housekeeping','Floor 1 Guest Wing','Water',1800,'L/day',1650,'2026-08-12 18:00','Normal','💧');
INSERT INTO METER_READINGS (METERID,DEPARTMENTID,ZONE,TYPE,BASELINEDAILY,UNIT,LASTREADING,LASTREADINGTIME,STATUS,ICON) VALUES ('MTR-E-F1','housekeeping','Floor 1 Guest Wing','Electricity',140,'kWh/day',132,'2026-08-12 18:00','Normal','⚡');
INSERT INTO METER_READINGS (METERID,DEPARTMENTID,ZONE,TYPE,BASELINEDAILY,UNIT,LASTREADING,LASTREADINGTIME,STATUS,ICON) VALUES ('MTR-W-F2','housekeeping','Floor 2 Guest Wing','Water',1750,'L/day',1710,'2026-08-12 18:00','Normal','💧');
INSERT INTO METER_READINGS (METERID,DEPARTMENTID,ZONE,TYPE,BASELINEDAILY,UNIT,LASTREADING,LASTREADINGTIME,STATUS,ICON) VALUES ('MTR-E-F2','housekeeping','Floor 2 Guest Wing','Electricity',145,'kWh/day',140,'2026-08-12 18:00','Normal','⚡');
INSERT INTO METER_READINGS (METERID,DEPARTMENTID,ZONE,TYPE,BASELINEDAILY,UNIT,LASTREADING,LASTREADINGTIME,STATUS,ICON) VALUES ('MTR-W-F3','housekeeping','Floor 3 Executive Wing','Water',1600,'L/day',2150,'2026-08-12 18:00','Anomaly Flagged (+34.3%)','💧');
INSERT INTO METER_READINGS (METERID,DEPARTMENTID,ZONE,TYPE,BASELINEDAILY,UNIT,LASTREADING,LASTREADINGTIME,STATUS,ICON) VALUES ('MTR-W-KIT','kitchen','Main Culinary Kitchen','Water',4500,'L/day',4320,'2026-08-12 21:00','Normal','💧');
INSERT INTO METER_READINGS (METERID,DEPARTMENTID,ZONE,TYPE,BASELINEDAILY,UNIT,LASTREADING,LASTREADINGTIME,STATUS,ICON) VALUES ('MTR-E-KIT','kitchen','Main Culinary Kitchen','Electricity',380,'kWh/day',460,'2026-08-12 21:00','Anomaly Flagged (+21.0%)','⚡');
INSERT INTO METER_READINGS (METERID,DEPARTMENTID,ZONE,TYPE,BASELINEDAILY,UNIT,LASTREADING,LASTREADINGTIME,STATUS,ICON) VALUES ('MTR-W-LDY','laundry','Commercial Eco-Laundry','Water',6200,'L/day',5890,'2026-08-12 20:30','Normal','💧');
INSERT INTO METER_READINGS (METERID,DEPARTMENTID,ZONE,TYPE,BASELINEDAILY,UNIT,LASTREADING,LASTREADINGTIME,STATUS,ICON) VALUES ('MTR-E-LDY','laundry','Commercial Eco-Laundry','Electricity',290,'kWh/day',275,'2026-08-12 20:30','Normal','⚡');
INSERT INTO METER_READINGS (METERID,DEPARTMENTID,ZONE,TYPE,BASELINEDAILY,UNIT,LASTREADING,LASTREADINGTIME,STATUS,ICON) VALUES ('MTR-E-HVAC','facilities','Central Chiller Plant','Electricity',850,'kWh/day',820,'2026-08-12 22:00','Normal','⚡');
INSERT INTO METER_READINGS (METERID,DEPARTMENTID,ZONE,TYPE,BASELINEDAILY,UNIT,LASTREADING,LASTREADINGTIME,STATUS,ICON) VALUES ('MTR-W-FAC','facilities','Maintenance Workshop','Water',500,'L/day',620,'2026-08-13 08:00','Anomaly Flagged (+24.0%)','💧');
INSERT INTO METER_READINGS (METERID,DEPARTMENTID,ZONE,TYPE,BASELINEDAILY,UNIT,LASTREADING,LASTREADINGTIME,STATUS,ICON) VALUES ('MTR-W-FO','front-office','Front Office & Lobby','Water',700,'L/day',680,'2026-08-13 08:00','Normal','💧');
INSERT INTO METER_READINGS (METERID,DEPARTMENTID,ZONE,TYPE,BASELINEDAILY,UNIT,LASTREADING,LASTREADINGTIME,STATUS,ICON) VALUES ('MTR-E-FO','front-office','Front Office & Lobby','Electricity',120,'kWh/day',148,'2026-08-13 08:00','Anomaly Flagged (+23.3%)','⚡');

COMMIT;

-- Table: REPAIR_TICKETS
CREATE TABLE REPAIR_TICKETS (
    ID VARCHAR2(64) PRIMARY KEY,
    TICKETNUMBER VARCHAR2(255),
    ZONE VARCHAR2(255),
    DEFECTCATEGORY VARCHAR2(255),
    DESCRIPTION VARCHAR2(255),
    SEVERITY VARCHAR2(255),
    ESTIMATEDLOSSRATE VARCHAR2(255),
    ESTIMATEDDAILYLOSSNUM NUMBER(10),
    RESOURCETYPE VARCHAR2(255),
    PRIORITY VARCHAR2(255),
    QUEUEPOSITION NUMBER(10),
    ASSIGNEDTECHNICIAN VARCHAR2(255),
    STATUS VARCHAR2(255),
    CREATEDAT VARCHAR2(255),
    NOTES VARCHAR2(255),
    PHOTODATAURL VARCHAR2(255)
);

INSERT INTO REPAIR_TICKETS (ID,TICKETNUMBER,ZONE,DEFECTCATEGORY,DESCRIPTION,SEVERITY,ESTIMATEDLOSSRATE,ESTIMATEDDAILYLOSSNUM,RESOURCETYPE,PRIORITY,QUEUEPOSITION,ASSIGNEDTECHNICIAN,STATUS,CREATEDAT,NOTES,PHOTODATAURL) VALUES ('TCK-8801','TK-2026-0812-01','Room 304 (Floor 3)','Bathroom Water Leak','Toilet flush valve continuously running water into bowl.','High','280 Liters / day',280,'Water','High',1,'Faizal Rahim','In Progress','2026-08-12 11:20','Inspected silent flapper seal leak; replacing silicone diaphragm.',NULL);
INSERT INTO REPAIR_TICKETS (ID,TICKETNUMBER,ZONE,DEFECTCATEGORY,DESCRIPTION,SEVERITY,ESTIMATEDLOSSRATE,ESTIMATEDDAILYLOSSNUM,RESOURCETYPE,PRIORITY,QUEUEPOSITION,ASSIGNEDTECHNICIAN,STATUS,CREATEDAT,NOTES,PHOTODATAURL) VALUES ('TCK-8803','TK-2026-0810-04','Room 102 (Floor 1)','Dripping Basin Faucet','Hot water basin tap dripping ~40 drops/min.','Normal','35 Liters / day',35,'Water','Normal',0,'Faizal Rahim','Completed','2026-08-10 14:00','Replaced internal ceramic cartridge. Leak fully halted.',NULL);

COMMIT;

-- Table: TECHNICIANS
CREATE TABLE TECHNICIANS (
    ID VARCHAR2(64) PRIMARY KEY,
    NAME VARCHAR2(255),
    SPECIALTY VARCHAR2(255),
    STATUS VARCHAR2(255),
    ACTIVETICKETS NUMBER(10),
    PHONE VARCHAR2(255)
);

INSERT INTO TECHNICIANS (ID,NAME,SPECIALTY,STATUS,ACTIVETICKETS,PHONE) VALUES ('TECH-01','Faizal Rahim','Plumbing & Hydraulics','Busy (Room 304 (Floor 3))',1,'+60 12-441 9021');
INSERT INTO TECHNICIANS (ID,NAME,SPECIALTY,STATUS,ACTIVETICKETS,PHONE) VALUES ('TECH-02','Ramesh Kumar','HVAC & Electrical','Available',0,'+60 17-883 1145');
INSERT INTO TECHNICIANS (ID,NAME,SPECIALTY,STATUS,ACTIVETICKETS,PHONE) VALUES ('TECH-03','Chong Wei','Smart Controls & Sensors','Available',0,'+60 19-332 7780');
INSERT INTO TECHNICIANS (ID,NAME,SPECIALTY,STATUS,ACTIVETICKETS,PHONE) VALUES ('TECH-04','Nurul Huda','General Facility & Mechanical','Available',0,'+60 13-902 4451');

COMMIT;

-- Table: USER_AUDIT
CREATE TABLE USER_AUDIT (
    ID VARCHAR2(64) PRIMARY KEY,
    TIMESTAMP VARCHAR2(255),
    USERID VARCHAR2(255),
    USERNAME VARCHAR2(255),
    ACTION VARCHAR2(255),
    TARGETKEY VARCHAR2(255),
    PREVIOUSVALUE VARCHAR2(255),
    NEWVALUE VARCHAR2(255),
    REASON VARCHAR2(255)
);

INSERT INTO USER_AUDIT (ID,TIMESTAMP,USERID,USERNAME,ACTION,TARGETKEY,PREVIOUSVALUE,NEWVALUE,REASON) VALUES ('AUD-9001','2026-08-01 10:00:14','USR-102','Zhen Bang (Tech Lead)','UPDATE_OPERATIONAL_BASELINE','water_per_room','200 L/room/day','180 L/room/day','Calibrated for new high-efficiency low-flow aerators installed across Tower A.');
INSERT INTO USER_AUDIT (ID,TIMESTAMP,USERID,USERNAME,ACTION,TARGETKEY,PREVIOUSVALUE,NEWVALUE,REASON) VALUES ('AUD-9002','2026-08-02 09:30:22','USR-103','Wan Ching (Facilities Dir)','UPDATE_OPERATIONAL_BASELINE','kitchen_power','420 kWh/day','380 kWh/day','Induction cooktop upgrade in main banquet kitchen completed.');
INSERT INTO USER_AUDIT (ID,TIMESTAMP,USERID,USERNAME,ACTION,TARGETKEY,PREVIOUSVALUE,NEWVALUE,REASON) VALUES ('AUD-9003','2026-08-03 14:15:08','USR-104','Sze Ping (Head Chef)','UPDATE_OPERATIONAL_BASELINE','buffet_food_waste','0.15 kg/guest','0.12 kg/guest','Stricter VM2026 culinary prep guidelines adopted.');
INSERT INTO USER_AUDIT (ID,TIMESTAMP,USERID,USERNAME,ACTION,TARGETKEY,PREVIOUSVALUE,NEWVALUE,REASON) VALUES (NULL,'2026-08-01 10:15','USR-101','Kar Hang','BASELINE_CALIBRATION','water_per_room','185','180','Installed new aerator standard');
INSERT INTO USER_AUDIT (ID,TIMESTAMP,USERID,USERNAME,ACTION,TARGETKEY,PREVIOUSVALUE,NEWVALUE,REASON) VALUES (NULL,'2026-08-02 09:30','USR-102','Wan Ching','BASELINE_CALIBRATION','kitchen_water','4800','4500','Quarterly efficiency review');
INSERT INTO USER_AUDIT (ID,TIMESTAMP,USERID,USERNAME,ACTION,TARGETKEY,PREVIOUSVALUE,NEWVALUE,REASON) VALUES (NULL,'2026-08-03 14:15','USR-103','Sze Ping','BASELINE_CALIBRATION','buffet_food_waste','0.15','0.12','Buffet tray optimization initiative');
INSERT INTO USER_AUDIT (ID,TIMESTAMP,USERID,USERNAME,ACTION,TARGETKEY,PREVIOUSVALUE,NEWVALUE,REASON) VALUES (NULL,'2026-08-05 11:20','USR-102','Wan Ching','BASELINE_CALIBRATION','hvac_chiller_power','900','850','New chiller firmware update');
INSERT INTO USER_AUDIT (ID,TIMESTAMP,USERID,USERNAME,ACTION,TARGETKEY,PREVIOUSVALUE,NEWVALUE,REASON) VALUES (NULL,'2026-08-10 16:45','USR-101','Kar Hang','SYSTEM_REPORT_GEN','compliance_pdf','N/A','Exported','Weekly management reporting');
INSERT INTO USER_AUDIT (ID,TIMESTAMP,USERID,USERNAME,ACTION,TARGETKEY,PREVIOUSVALUE,NEWVALUE,REASON) VALUES (NULL,'2026-08-11 08:20','USR-104','System Scheduler','AUTO_ANOMALY_SCAN','utilityMeters','Scan Run','3 Alerts Found','Daily morning scan');
INSERT INTO USER_AUDIT (ID,TIMESTAMP,USERID,USERNAME,ACTION,TARGETKEY,PREVIOUSVALUE,NEWVALUE,REASON) VALUES (NULL,'2026-08-12 13:10','USR-101','Kar Hang','ROLE_PERMISSION_GRANT','USR-108','Staff','Facilities Manager','Promotion applied in HR system');

COMMIT;
